{% set version = "3.7.0" %}

package:
  name: singularity
  version: {{ version }}

source:
  - folder: src/github.com/sylabs/singularity
    url: https://github.com/sylabs/singularity/releases/download/v{{ version }}/singularity-{{ version }}.tar.gz
    sha256: fb96aaf5f462a56a4a5bd2951287bcbbefe8cf543e228e4e955428f386a8d478
    patches:
      - patches/0001-Make-runtime-relocatable.diff
      - patches/0002-Fix-configuration-for-conda-forge.patch
      - patches/0003-Use-external-CNI.patch
      - patches/set-version-from-env.patch

build:
  number: 0
  skip: true  # [not linux]
  # The binary is made runtime relocatable using the included patch
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cgo') }}
    - make
    - pkg-config
    - go-dep
    - sed
  host:
    - libuuid  # [linux]
    - libarchive
    - libseccomp  # [linux]
    - openssl
  run:
    # CNI version from singularity/Gopkg.lock
    - cni-plugins >=0.7.4  # [linux]
    - squashfs-tools  # [linux]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
    - singularity --help
    - singularity --version

    # Ensure the version is set correctly
    - singularity --version | grep {{ version }}

    # Ensure we are using conda's CNI
    - test ! -d $PREFIX/libexec/singularity/cni
    - test -d $PREFIX/lib/cni

    - test ! -d $PREFIX/etc/singularity/network
    - test -f $PREFIX/etc/cni/net.d/00_bridge.conflist

    # UserNS test
    - singularity build --sandbox lolcow docker://godlovedc/lolcow

    # Either run the container or fail due to user namespaces being disabled
    - "singularity --verbose --debug run -u lolcow || (singularity --verbose --debug run -u lolcow 2>&1 | grep 'Failed to create user namespace: user namespace requires to set')"

about:
  home: https://www.sylabs.io/singularity/
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/github.com/sylabs/singularity/LICENSE-LBNL.md
  summary: 'Singularity: Application containers for Linux'

  description: |
    Singularity is a container platform focused on supporting "Mobility of
    Compute"

    Mobility of Compute encapsulates the development to compute model where
    developers can work in an environment of their choosing and creation and
    when the developer needs additional compute resources, this environment
    can easily be copied and executed on other platforms. Additionally as the
    primary use case for Singularity is targeted towards computational
    portability, many of the barriers to entry of other container solutions do
    not apply to Singularity making it an ideal solution for users (both
    computational and non-computational) and HPC centers.

  dev_url: https://github.com/singularityware/singularity
  doc_url: https://www.sylabs.io/docs/

extra:
  recipe-maintainers:
    - bgruening
    - jakirkham
    - sodre
    - chrisburr
