appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Lypu/QLjlaWEIZvDrYmbBJ3SS1FWSOLPRcjlu0R+4NNGXfLTUjI1fjQQ7nDjMS4GZnbTS56dqHRXmHg1YS39jkVwiHNCfsUco+5PYNWm/mDHTikZlVJuExW3YjIcnNJ9t1sDSad7/vJiCBS2RtARffgtUih1c7pZcuKMlu6LE4UhOrtByWMO2OzrJhjPRKonOGcaV8/iacv5vs0xceGCH+kCv0WNA09rv+fHESX8FmkGhTD/gmuxwiDXWMDHDrPAQWl/aZT6Hix2VlaE56721XscyZprd1slKALBR/E8nzuobSWZe4ZDX22SqGc500yXwaa7qcCUvssb/AUGl3Y5sE3RZ/8iMfZ7GMUGNOndBWxcWrBmUDweMv7fcRiNwC8x4L4yGP8TuCFzROnCqjaWJO8xYYBR9r//HunFiY07wzfKMWa7Vs+JM2KRpmwDr9awoLglMAcwEaYE/Cf4WjY5E2Ppj78ptZGjf7yekYo0ACHB1Walb5E8SmytvhejSZtSkEUOlvQ3B6Am2C9ooRyZiOM+LZ+vvViRMBZjJo4cUj9Y1V/l0xh3llYnvOBHtN1H+dZ8wxW1NsW9QFXg/SwZ6kFz2ObV0E6VMirDblDnxsabMZfcXkFqmVscNI9of59DBdqWLHh9eNwwnmI1NAUFMIwbuw6kBxZLGc4m/jhFYvM=}
